### ISSUE TITLE
error: use of overloaded operator in mpegaudioframe.cpp:55:123

### ISSUE THREAD

**Issue by buckmanhands** [Martchus/tagparser#19]
I was trying to compile tageditor on a mac (Big Sur) and tagparser is a dependency and I ran into this error at the "make" stage.

```
tagparser/mpegaudio/mpegaudioframe.cpp:55:123: error: use of overloaded operator '-' is ambiguous (with operand types 'std::basic_istream<char>::pos_type' (aka 'fpos<__mbstate_t>') and 'long')
            "Frame 0x" % numberToString(m_header, 16u) % " at 0x" % numberToString<std::int64_t>(reader.stream()->tellg() - 4l, 16) + " is invalid.",
                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/string:555:37: note: candidate function
    _LIBCPP_INLINE_VISIBILITY fpos  operator- (streamoff __off) const {fpos __t(*this); __t -= __off; return __t;}
                                    ^
../tagparser/mpegaudio/mpegaudioframe.cpp:55:123: note: built-in candidate operator-(long long, long)
            "Frame 0x" % numberToString(m_header, 16u) % " at 0x" % numberToString<std::int64_t>(reader.stream()->tellg() - 4l, 16) + " is invalid.",
```
I just made that line throw a static error since I did not know how to fix it, and then it installed fine.

For those trying to install on a mac, be absolutely sure you have the latest xCode Command Line Tools installed. After I installed them, it was not until I ran `brew doctor` that I became aware that a fresh install of those tools was not the latest version and it needed to be updated. Running `brew doctor` will give you the command to force the latest xCode CLT.

**Comment by Martchus** [comment]
I don't use a Mac myself so this environment is definitely not tested. Maybe I can reproduce the problem under Linux using libc++, though.

If you can come up with a better patch (than just making it a static message), you're welcome to contribute.

**Comment by Martchus** [comment]
That's also reproducible under GNU/Linux when using the latest version of libc++. So it is the standard library which seems to make the difference here. I'll try to fix it.

**Comment by buckmanhands** [comment]
If I can figure out how to code it I will definitely pass it along here. My main goal was to get the program compiled and see if it works. It does, so I may be able to spend some time figuring out how to fix that. I would definitely like to hear if you can recreate it on other platforms.

**Comment by Martchus** [comment]
> I would definitely like to hear if you can recreate it on other platforms.

I assume you haven't seen my previous comment when replying.

The issue should be fixed by https://github.com/Martchus/tagparser/commit/cb52a1521e003a1133fc98c7ff005b778c7d3a26.
