### ISSUE TITLE
Build tagparser without OpenSSL

### ISSUE THREAD

**Issue by Martchus** [Martchus/tagparser#2]
https://github.com/Martchus/tageditor/issues/13#issuecomment-294323474:

> Still does not work without OpenSSL:
> 
> ~~~
> CMake Error: The following variables are used in this project, but they are set
> to NOTFOUND. Please set them or make sure they are set and tested correctly in
> the CMake files:
> OPENSSL_INCLUDE_DIR (ADVANCED)
>    used as include directory in directory /var/cache/glade/tagparser
> ~~~

Not sure why it worked when I tested a few hours ago. Need to further investigate this.

**Comment by Martchus** [comment]
I tested by changing the library name (crypto) and CMake package name (OpenSSL) to something which does not exist on my system. I can't just uninstall OpenSSL here because it would break too many things. I only get the intended warning:

```
CMake Warning at .../projects/c++/cmake/c++utilities/cmake/modules/3rdParty.cmake:126 (find_package):
  By not providing "FindOpenSSLl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenSSLl",
  but CMake did not find one.
...
CMake Warning at .../projects/c++/cmake/c++utilities/cmake/modules/3rdParty.cmake:73 (message):
  External library cryptol required by tagparser is not available for the
  specified linkage AUTO_LINKAGE.
Call Stack (most recent call first):
  .../projects/c++/cmake/c++utilities/cmake/modules/3rdParty.cmake:96 (link_against_library_varnames)
 .../projects/c++/cmake/tagparser/CMakeLists.txt:193 (link_tests_against_library)


CMake Warning at .../projects/c++/cmake/tagparser/CMakeLists.txt:198 (message):
  Unable to check testfile integrity because OpenSSL is not available.
```

@svnpenn Did you clear the CMake cache?

**Comment by svnpenn** [comment]
Just tried this again with a pristine virtual machine. it does not work with Cygwin currently with OpenSSL installed. Full stop.

**Comment by Martchus** [comment]
My previous test by just changing the library name was indeed not sufficient. The issue should be fixed inhttps://github.com/Martchus/cpp-utilities/commit/ecce539a187d75a0c68e3636ec4b720c2ffc0ea4.

**Comment by svnpenn** [comment]
@Martchus confirmed fixed. Thanks
