### ISSUE TITLE
cmake failed. Format rules for clang-format not found.

### ISSUE THREAD

**Issue by 3togo** [Martchus/tagparser#21]
How to solve this problem?

-- Linking tagparser against special library for std::filesystem support is not required.
-- Found required OpenSSL targets (OpenSSL::Crypto)
-- Configuring project tagparser
-- Using default CXX11 ABI  of libstdc++ (not forcing old CX11 ABI).
CMake Warning at /usr/local/share/c++utilities/cmake/modules/BasicConfig.cmake:353 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  CMakeLists.txt:203 (include)

**Comment by Martchus** [comment]
It should definitely work without `clang-format`. I conduct all my Arch Linux package builds in a minimal environment without it. That's just a warning. I assume the real error is logged somewhere before.

**Comment by 3togo** [comment]
what cmake option could be used to avoid it ?

**Comment by Martchus** [comment]
Like I said, the formatting/tidying is likely not a problem (unless explicitly enabled) and "Format rules for clang-format not found." is just a warning. Show me the full log and invocation and maybe I can help.

**Comment by Martchus** [comment]
By the way, have you seen these build instructions? https://github.com/Martchus/tageditor#building-this-straight

If you don't need the tag editor you can just remove its directory from the subdirs CMake file.

**Comment by 3togo** [comment]
many thanks. Will try it
