### ISSUE TITLE
Build Instructions Abmiguous About the "cpp-utilities" Dependency

### ISSUE THREAD

**Issue by SentToDevNull** [Martchus/tagparser#3]
You should probably link https://github.com/Martchus/cpp-utilities directly in your README.md because it's not obvious that you are referring another one of your own repositories when you say that "cpp-utilities" is required for CMake.

**Comment by Martchus** [comment]
True, I've already linked it in tageditor (another of my own repos) but forgot to update the README.md of tagparser.

> when you say that "cpp-utilities" is required for CMake

Where do I say that in the README.md? c++utilities is required for both - additional CMake modules and the utilities library itself.

**Comment by SentToDevNull** [comment]
It's under the Build Instructions heading where you say "The tagparser library depends on c++utilities". Would probably be useful to change that to "The tagparser library depends on the c++utilities library located [here](https://github.com/Martchus/cpp-utilities)".

**Comment by Martchus** [comment]
It is linked now.

About the fact that it requires CMake modules as well as the actual library from c++utilities project: You shouldn't care much about about it. Just build c++utilities like any other CMake project and ensure it is found when building tagparser. You don't need to know any details like which parts from c++utilities repo are exactly used by tagparser.

But thanks for the feedback. It seems like you're only there for the library and not the tag editor application. Just out of interest, for what do you want to use it?

**Comment by SentToDevNull** [comment]
@Martchus I love how simple this is to use, so I'm using it in an audiobook encoder and organizer program I'm making. It needs to be able to rip tags from all imported media so that I can algorithmically choose which tags to apply to my encoded audiobooks and sort them by. When it's somewhat usable, I'll release it under the same GPLv2 license. Once again, thanks for the awesome work!

**Comment by Martchus** [comment]
Sounds interesting. I'll check it out when you publish it.

Since it is linked now, I'm closing the issue.
